version: '3.8'

services:
  app:
    build:
      context: .
    image: visitor-app
    container_name: visitor-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: visitor-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visitor
      MYSQL_USER: visitor
      MYSQL_PASSWORD: visitor
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: visitor-redis
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:

  reverb:
    image: laravelphp/php-fpm
    container_name: visitor-reverb
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php artisan reverb:start
    depends_on:
      - redis
    ports:
      - "6001:6001"
    networks:
      - laravel